---
dependency:
  name: galaxy

driver:
  name: docker 

platforms:
  - name: instance
    groups:
      - test
    ansible_connection: local  # Подключение как к локальному хосту

verifier:
  name: testinfra

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        roles_path:
          - ../../  # Указываем путь к корню проекта  
