---
dependency:
  name: galaxy

driver:
  name: docker 

platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: true

verifier:
  name: testinfra

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        roles_path:
          - ../../  # Указываем путь к корню проекта 