---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker 

platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    privileged: true
    pre_build_image: true


provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        roles_path:
          - ../../  # Указываем путь к корню проекта  


verifier:
  name: ansible  # Отключаем Testinfra, оставляем пустой Verifier

scenario:
  name: default
  prepare: {}
  cleanup: {}          



